/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orthostereogram;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Fred
 */
public class JPanelCalib extends javax.swing.JPanel {

    int r = -65536 ;
    int c = -16711681 ;
    
    /**
     * Creates new form JPanelCalib
     */
    public JPanelCalib() {
        initComponents();
        
        if (NewController.isCalibrated) jCurrentCalib.setBackground(Color.GREEN);
        else jCurrentCalib.setBackground(Color.RED);
        
        jRED.setBackground(new Color (r) );
        jCYAN.setBackground(new Color (c) );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRED = new javax.swing.JPanel();
        jSliderRed = new javax.swing.JSlider();
        jCYAN = new javax.swing.JPanel();
        jSliderCyan = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCurrentCalib = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jRED.setBackground(java.awt.Color.red);

        javax.swing.GroupLayout jREDLayout = new javax.swing.GroupLayout(jRED);
        jRED.setLayout(jREDLayout);
        jREDLayout.setHorizontalGroup(
            jREDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jREDLayout.setVerticalGroup(
            jREDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        jCYAN.setBackground(java.awt.Color.cyan);

        javax.swing.GroupLayout jCYANLayout = new javax.swing.GroupLayout(jCYAN);
        jCYAN.setLayout(jCYANLayout);
        jCYANLayout.setHorizontalGroup(
            jCYANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jCYANLayout.setVerticalGroup(
            jCYANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        jSliderCyan.setMaximum(5);
        jSliderCyan.setMinimum(-5);
        jSliderCyan.setValue(0);
        jSliderCyan.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderCyanStateChanged(evt);
            }
        });

        jLabel1.setText("Calibration du rapport de vergence en fonction de la taille de l'écran :");

        jButton1.setText("Calibrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Calibration courante : ");

        jCurrentCalib.setEditable(false);
        jCurrentCalib.setText("10");
        jCurrentCalib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCurrentCalibActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSliderCyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jSliderRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCYAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jCurrentCalib, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCurrentCalib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCYAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderCyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderCyanStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderCyanStateChanged
        int a  = jSliderCyan.getValue() ;
        //System.out.println (hue) ;
        Color t = new Color (c) ;
               
        float[] hsb = Color.RGBtoHSB(t.getRed(), t.getGreen(), t.getBlue(), null);
        
        float hue = hsb[0];
        float saturation = hsb[1];
        float brightness = hsb[2];
        //Make changes
        
        Color b = new Color(Color.HSBtoRGB( hue + (float) a  / 100.0f, hsb[1], hsb[2]));
        /*//Repaint color
        int rgb = Color.HSBtoRGB(hue, saturation, brightness);
        jCYAN.setBackground(new Color (rgb) );
        //repaint () ;*/
        
        //Color b = new Color(t.getRed(), t.getGreen(), t.getBlue(), a );
        jCYAN.setBackground( b );
        repaint () ;
    }//GEN-LAST:event_jSliderCyanStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Calibrate cal = new Calibrate ((JFrame) SwingUtilities.getWindowAncestor(this), true) ;
        cal.setLocationRelativeTo(this);
        cal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCurrentCalibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCurrentCalibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCurrentCalibActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jCYAN;
    private javax.swing.JTextField jCurrentCalib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jRED;
    private javax.swing.JSlider jSliderCyan;
    private javax.swing.JSlider jSliderRed;
    // End of variables declaration//GEN-END:variables
}
